# config.yaml

worker:
  replicas: 8
  limits:
    cpu: 4
    memory: 26 GiB
  pipPackages: >-
    git+https://github.com/dask/gcsfs.git
    git+https://github.com/ioam/holoviews.git
    git+https://github.com/ahuang11/holoext.git
    git+https://github.com/pydata/xarray.git
    git+https://github.com/scikit-learn-contrib/imbalanced-learn.git
  condaPackages: >-
    -c conda-forge
    fastparquet
    pyarrow
    seaborn
    bokeh
    scikit-learn



# We want to keep the same packages on the worker and jupyter environments
jupyter:
  pipPackages: >-
    git+https://github.com/dask/gcsfs.git
    git+https://github.com/ioam/holoviews.git
    git+https://github.com/ahuang11/holoext.git
    git+https://github.com/pydata/xarray.git
    git+https://github.com/scikit-learn-contrib/imbalanced-learn.git
  condaPackages: >-
    -c conda-forge
    fastparquet
    pyarrow
    seaborn
    bokeh
    scikit-learn
